# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84f30dfca03ea90224c9b85ba6f7dfdd9c6c864baf51532773f7634abdefaf3ed7ab03ae3cb48ff3a3043275eb2db6b4fe8074512ac83cab910ee81b771810f2

test:
  secret_key_base: 61c366518ccc19bf5c9186ca337d9e6e7eacb0f20d603496254b6ee98aed8a3e5bb3e4d90b24d344e0654dc20029ab8d74561588225899533a379f43096c1531

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
